
#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "目前在LINE Taiwan 擔任 Backend Engineer Intern"
author = "Evan Lin"
# Contact Information
mobile = ""
email = "drose01rrr@gmail.com"
location = ""
# copyright
copyright = "| copyright &copy; 2025 [Evan](https://themefisher.com/hugo-themes/) All Rights Reserved |"


[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"



# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/yifan00802/"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/YIFUNLIN"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/lin-yi-fan-293082257/"

[markup]
  [markup.highlight]
    style = 'abap'  # monokai
